### ISSUE TITLE
Odświeżenie interfejsu aplikacji

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [Sealious/sealious-example-app#1]
Myślę, że warto byłoby troszeczkę odświeżyć layout zwłaszcza w menu. Co sądzicie? Mamy jeszcze stare zaszłości Prometeusza w interfejsie :)

**Comment by simplypixi** [comment]
Jak już milion razy mówiłem (;p), nowy szkielet jest zrobiony tylko do tej
pory nie znalazłem czasu żeby go podpiąć pod example-app (trzeba
przebudować solidnie example-app). Mogę Ci podesłać ten szkielet.
Upiększysz go, a później zajmiemy się przypięciem. Z drugiej strony mam
teraz więcej czasu i z chęcią najpierw podepnę szkielet. Myślę, że będzie
Ci się lepiej pracować, na działającym szkielecie z danymi. ;)

W dniu 10 kwietnia 2015 23:10 użytkownik Arkadiusz Wieczorek <
notifications@github.com> napisał:

> Myślę, że warto byłoby troszeczkę odświeżyć layout zwłaszcza w menu. Co
> sądzicie? Mamy jeszcze stare zaszłości Prometeusza w interfejsie :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Sealious/sealious-example-app/issues/1.
> 
> Mariusz Wójcik
> tel. 507-386-287

Napisz wiadomość >> pixiproject@gmail.com
Przejdź do portfolio >> http://simplypixi.portfoliobox.me/projects
[image: 2]
http://oferia.pl/wykonawca/pixel93/323171?utm_source=powiad&utm_medium=email&utm_campaign=sygnatura_mail

W dniu 10 kwietnia 2015 23:10 użytkownik Arkadiusz Wieczorek <
notifications@github.com> napisał:

**Comment by arkadiusz-wieczorek** [comment]
ok lepiej będzie kiedy go najpierw dopniemy :)

**Comment by kuba-orlik** [comment]
Chat już dawno nie jest na naszej liście tasków, zamykam
